- name: Shuttle Legacy Deployment
  hosts: shuttle_legacy
  tasks:
    - name: Get Tag
      include_role:
        name: git-fetch-tag
    - name: Build
      make:
        chdir: "{{ install_dir }}"
        target: all
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"


- name: Shuttle Servers Deployment
  hosts: shuttle_servers
  tasks:
    - name: Get Tag
      include_role:
        name: git-fetch-tag
    - name: Build
      make:
        chdir: "{{ install_dir }}"
        target: all
    - name: Stop the process (nginx and api node)
      shell: |
        systemctl stop nginx.service
        systemctl stop estuary-shuttle.service
    - name: Copy from build to bin
      shell: |
        cd "{{ install_dir }}"
        cp estuary-shuttle /usr/local/bin/
    - name: Start the process (api node and nginx)
      shell: |
        systemctl restart nginx.service
        systemctl restart estuary-shuttle.service