- name: Gateways
  hosts: gateway_servers
  tasks:
    - name: Get Tag
      include_role:
        name: git-fetch-tag
    - name: Build and Install
      shell: |
        systemctl stop s5-gateway.service
        go build -tags netgo -ldflags '-s -w' -o shuttle-5-gw
    - name: Restart
      shell: |
        systemctl restart s5-gateway.service
        systemctl restart nginx.service