- name: Shuttle-1 Deployment
  remote_user: root
  hosts: shuttle_1
  tasks:
     - name: Make sure we have Go
       shell: |
        whoami
        uptime & uname -a
        export GOPATH=$HOME/go
        export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
     - name: Build 
       shell: |
        cd /home/why/code/estuary
        git fetch --tags
        git checkout {{tag}}
        git pull origin {{tag}}
        make all

- name: Shuttle-2 Deployment
  remote_user: estuary
  hosts: shuttle_2
  tasks:
     - name: Make sure we have Go
       shell: |
        whoami
        uptime & uname -a
        export GOPATH=$HOME/go
        export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
     - name: Build 
       shell: |
        cd /home/estuary/code/estuary
        git fetch --tags
        git checkout {{tag}}
        git pull origin {{tag}}
        make all

- name: Shuttle Server Deployment
  remote_user: root
  hosts: shuttle_servers
  tasks:
     - name: Execute the script
       shell: |
        whoami
        uptime & uname -a
        cd /home/estuary/source/estuary/
        git fetch --tags
        git checkout {{tag}}
        git pull origin {{tag}}
        make all
     - name: Stop the process (nginx and api node)
       shell: |
        systemctl stop nginx.service
        systemctl stop estuary-shuttle.service
     - name: Copy from build to bin
       shell: | 
        cd /home/estuary/source/estuary/
        cp estuary-shuttle /usr/local/bin/
     - name: Start the process (api node and nginx)
       shell: |
        systemctl restart nginx.service
        systemctl restart estuary-shuttle.service


