- name: Shuttle-6 Deployment
  remote_user: root
  hosts: shuttle_servers
  tasks:
     - name: Execute the script
       shell: |
        whoami
        uptime & uname -a
        cd /home/estuary/source/estuary/
        git fetch --tags
        git checkout {{tag}}
        git pull origin {{tag}}
        make all
     - name: Stop the process (nginx and api node)
       shell: |
        systemctl stop nginx.service
        systemctl stop estuary.service
     - name: Copy from build to bin
       shell: | 
        cd /home/estuary/source/estuary/
        cp estuary /usr/local/bin/
     - name: Start the process (api node and nginx)
       shell: |
        systemctl restart nginx.service
        systemctl restart estuary-shuttle.service

- name: Shuttle-7 Deployment
  remote_user: root
  hosts: shuttle_servers
  tasks:
     - name: Execute the script
       shell: |
        whoami
        uptime & uname -a
        cd /root/estuary/
        git fetch --tags
        git checkout {{tag}}
        git pull origin {{tag}}
        make all
     - name: Stop the process (nginx and node)
       shell: |
        systemctl stop nginx.service
        systemctl stop estuary.service
     - name: Copy from build to bin
       shell: | 
        cd /root/estuary
        cp estuary /usr/local/bin/
     - name: Start the process (node and nginx)
       shell: |
        systemctl restart nginx.service
        systemctl restart estuary-shuttle.service


- name: Shuttle-8 Deployment
  remote_user: root
  hosts: shuttle_servers
  tasks:
     - name: Execute the script
       shell: |
        whoami
        uptime & uname -a
        cd /root/estuary/
        git fetch --tags
        git checkout {{tag}}
        git pull origin {{tag}}
        make all
     - name: Stop the process (nginx and node)
       shell: |
        systemctl stop nginx.service
        systemctl stop estuary.service
     - name: Copy from build to bin
       shell: | 
        cd /root/estuary
        cp estuary /usr/local/bin/
     - name: Start the process (node and nginx)
       shell: |
        systemctl restart nginx.service
        systemctl restart estuary-shuttle.service

